# Generated by Django 4.0.4 on 2022-05-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('kind', models.CharField(max_length=5)),
                ('content_advisory_rat', models.CharField(max_length=255)),
                ('artwork_url100', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreId', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('genre_url', models.URLField()),
                ('genre_trackId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_songs.track')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistId', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('artist_url', models.URLField()),
                ('artist_trackId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='top_songs.track')),
            ],
        ),
    ]
