# Generated by Django 4.0.4 on 2022-05-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('kind', models.CharField(max_length=5)),
                ('content_advisory_rat', models.CharField(max_length=255)),
                ('artwork_url100', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreId', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('genre_url', models.URLField()),
                ('genre_track', models.ManyToManyField(related_name='genres', to='top_songs.track')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistId', models.CharField(max_length=255, unique=True)),
                ('artist_name', models.CharField(max_length=255)),
                ('artist_url', models.URLField()),
                ('artist_track', models.ManyToManyField(related_name='artist', to='top_songs.track')),
            ],
        ),
    ]
