# Generated by Django 3.2.7 on 2022-05-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_trackId',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_trackId',
            field=models.ManyToManyField(to='top_songs.Track'),
        ),
    ]
