# Generated by Django 4.0.4 on 2022-05-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_songs', '0002_alter_artist_artistid_alter_genre_genreid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artistId',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='registry',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_track',
            new_name='track',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genreId',
            new_name='registry',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='track_id',
            new_name='registry',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre_track',
        ),
        migrations.AddField(
            model_name='genre',
            name='track',
            field=models.ManyToManyField(related_name='genre', to='top_songs.track'),
        ),
    ]
